# QF627 Pre-Course Workshop | Introduction to Programming

## Lesson 2 | An Introduction to `NumPy` | `RE`view

> In the previous lesson, you have learned about `methods and functions` that are available in built-in Python, along with variables and data types.

> First, let us begin with some basic built-in Python that you need to fully understand before we proceed.

> Here's a quick reminder regarding the useful hotkeys for scripting on Jupyter Notebook :)

- `a` inserts a cell above 
- `b` inserts a cell below
- `dd` (double d) deletes a cell 
- `esc` jumps out of the cell
- `return/enter` gets into the cell
- `m` makes your cell markdown
- `y` makes your cell code
- `shift + control + -` splits the cell
- `shift + m` merges the cells
- `shift + l` adds line numbers into the cell

> Now you will start learning about how to use `packages`.

> As Python is open-source language, using the humongous ecosystem of packages will help you work more efficiently.

> A `package is a collection of Python modules and scripts` giving you new data types, functions, and methods.


### How to `install` a ***package***?

> To use a package, you need to download it first.

> Let's use the command `pip3 install target_package` so that you can install packages of your interest.

> For downloading a package, you need to do this just once, yet you should import in your workspace whenever you wish to use it.

> The command below will load the NumPy package into Python for your use.

In [1]:
!pip install numpy


[notice] A new release of pip is available: 23.1.2 -> 23.2.1
[notice] To update, run: pip install --upgrade pip


In [2]:
%whos

Interactive namespace is empty.


In [3]:
import numpy as np

In [4]:
%whos

Variable   Type      Data/Info
------------------------------
np         module    <module 'numpy' from '/Us<...>kages/numpy/__init__.py'>


In [5]:
dir(numpy)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'Bytes0',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'Datetime64',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Str0',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'Uint64',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__deprecated_attrs__',
 '__dir__',
 '__doc__',
 '__expired_functions__',
 '__file__',
 '__getattr__',
 '__git_version__',
 '__loader__',


***Wait, why do we use alias here (i.e., as `np`)? ?*** 

> As you will see below, 

- To access the array() function, you need to use np.array() to indicate that the function is from the NumPy package.

> Yes, the reason why we have used np as alias is to minimize our typing task.

### The Basics

> Using `NumPy`, you can create a new data type called `array`.

> Why use data type `array`?

**`array` is useful for financial analysis because...**

- array `stores` data more efficiently

- array `performs` faster than built-in Python lists in terms of computations (access in reading and writing items faster as the package is optimized for numerical analyses)

- array `shows` better performance with relatively larger datasets

- array, most importantly, **`enables` you to utilize `array-related functions`**--you can perform statistical modelling and visualization easier, which is critical for financial analysis.





> **A good way to understand about the usefulness of NumPy is to compare array with list (yes, that list that you learned in the previous lesson).**

#### Differences 1. Arrays can contain only a single data type (unlike lists).

In [8]:
sample_list = ["Year", 2023, True]

In [9]:
sample_list

['Year', 2023, True]

In [10]:
type(sample_list)

list

In [11]:
type(sample_list[0]
    )

str

In [12]:
type(sample_list[1]
    )

int

In [13]:
type(sample_list[-1]
    )

bool

> As you will see below, arrays in NumPy will convert the elements in the list to the most compatible data types.

In [14]:
our_first_array =\
    np \
    .array(["Year", 2023, True]
          )

In [15]:
type(our_first_array)

numpy.ndarray

In [16]:
%whos

Variable          Type       Data/Info
--------------------------------------
np                module     <module 'numpy' from '/Us<...>kages/numpy/__init__.py'>
numpy             module     <module 'numpy' from '/Us<...>kages/numpy/__init__.py'>
our_first_array   ndarray    3: 3 elems, type `<U21`, 252 bytes
sample_list       list       n=3


In [17]:
print(our_first_array)

['Year' '2023' 'True']


In [18]:
# Here are lists.
earnings_list = [10.09, 10.28, 2.21, 6.19, 8.24]
prices_list = [99.98, 87.68, 154.23, 162.12, 121.11]

> How would you make objects `earnings` and `prices` arrays?

In [19]:
earnings_array = np.array(earnings_list)
prices_array = np.array(prices_list)

print(earnings_array);print(prices_array)

[10.09 10.28  2.21  6.19  8.24]
[ 99.98  87.68 154.23 162.12 121.11]


#### Differences 2. Arrays have different ways of operations (than lists).

In [20]:
prices_list

[99.98, 87.68, 154.23, 162.12, 121.11]

In [21]:
earnings_list

[10.09, 10.28, 2.21, 6.19, 8.24]

In [23]:
pe_ratio_list = prices_list + earnings_list
print(pe_ratio_list)

[99.98, 87.68, 154.23, 162.12, 121.11, 10.09, 10.28, 2.21, 6.19, 8.24]


In [ ]:
# in case that you wish to run vectorized computation in built-in Python list
# you could still run element-wise operations

In [24]:
element_wise_list = []

In [25]:
for first, second in zip(prices_list, earnings_list):
    element_wise_list.append(first + second)

In [26]:
len(element_wise_list)

5

In [27]:
element_wise_list

[110.07000000000001, 97.96000000000001, 156.44, 168.31, 129.35]

> Let's see how lists behave first.

In [ ]:
pe_ratio_list = prices_list + earnings_list
print(pe_ratio_list)

> The two objects were merely concatenated. That's not what we want...

In [28]:
PE_ratio_array = prices_array / earnings_array
print(PE_ratio_array)

[ 9.90882061  8.52918288 69.78733032 26.19063005 14.69781553]


> ***Arrays allow for efficient numerical manipulation of its elements.***

> Let's calculate `the dollar amount an investor can expect to invest in a company to receive one dollar of that company’s earnings`--yes, the `price to earnings ratio`--using two arrays, earnings_array and prices_array above.

In [ ]:
pe_ratio_array = prices_array / earnings_array

print(pe_ratio_array)

> You could see here that arrays perform `element-wise mathematical operations`.

#### Indexing, Subsetting, Filtering, & Slicing: Similarities between `array` and `list`

> We have seen differences between arrays and lists.

> Here are also similarities.

In [29]:
%whos

Variable            Type       Data/Info
----------------------------------------
PE_ratio_array      ndarray    5: 5 elems, type `float64`, 40 bytes
earnings_array      ndarray    5: 5 elems, type `float64`, 40 bytes
earnings_list       list       n=5
element_wise_list   list       n=5
first               float      121.11
np                  module     <module 'numpy' from '/Us<...>kages/numpy/__init__.py'>
numpy               module     <module 'numpy' from '/Us<...>kages/numpy/__init__.py'>
our_first_array     ndarray    3: 3 elems, type `<U21`, 252 bytes
pe_ratio_list       list       n=10
prices_array        ndarray    5: 5 elems, type `float64`, 40 bytes
prices_list         list       n=5
sample_list         list       n=3
second              float      8.24


In [30]:
earnings_list

[10.09, 10.28, 2.21, 6.19, 8.24]

In [32]:
earnings_list[1:-1]

[10.28, 2.21, 6.19]

In [34]:
subset_earnings_list = earnings_list[1:-1]

In [35]:
earnings_list[1:-1] == subset_earnings_list

True

In [33]:
earnings_array[1:-1]

array([10.28,  2.21,  6.19])

In [36]:
subset_earnings_array = earnings_array[1:-1]

In [37]:
earnings_array[1:-1] == subset_earnings_array

array([ True,  True,  True])

> Please address the error message above.

### Arrays in NumPy can be `multi`dimensional.

![](ndim.png)
#### How to add image (CLICK HERE TWICE)

> A common form of financial data comes with a rectangular form of data that contains rows and columns. 

> Such data can be represented with two-dimensional arrays.

> To create a two-dimensional array using NumPy, you can use the same function array().

> Instead of providing a single list as your input, let's pass in a list of two lists as your input.

> Here, let's pass earnings and prices to create a two-dimensional array.

In [38]:
list_NESTED = [[10.09, 10.28, 2.21, 6.19, 8.24],[99.98, 87.68, 154.23, 162.12, 121.11]]
print(list_NESTED)

[[10.09, 10.28, 2.21, 6.19, 8.24], [99.98, 87.68, 154.23, 162.12, 121.11]]


In [39]:
list_NESTED[1][-2]

162.12

In [5]:
pe_array = np.array([[10.09, 10.28, 2.21, 6.19, 8.24],[99.98, 87.68, 154.23, 162.12, 121.11]])
print(pe_array)

# Recall that there were two lists of earnings_list and prices_list


[[ 10.09  10.28   2.21   6.19   8.24]
 [ 99.98  87.68 154.23 162.12 121.11]]


In [41]:
np.array([earnings_list, prices_list]) == pe_array

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

> You might want to use `boolean` arrays as well. 

> As you will see below, Boolean arrays are quite useful for subsetting--stay tuned :)

#### Methods in Array

In [42]:
dir(pe_array)

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__

In [43]:
help(pe_array.astype)

Help on built-in function astype:

astype(...) method of numpy.ndarray instance
    a.astype(dtype, order='K', casting='unsafe', subok=True, copy=True)
    
    Copy of the array, cast to a specified type.
    
    Parameters
    ----------
    dtype : str or dtype
        Typecode or data-type to which the array is cast.
    order : {'C', 'F', 'A', 'K'}, optional
        Controls the memory layout order of the result.
        'C' means C order, 'F' means Fortran order, 'A'
        means 'F' order if all the arrays are Fortran contiguous,
        'C' order otherwise, and 'K' means as close to the
        order the array elements appear in memory as possible.
        Default is 'K'.
    casting : {'no', 'equiv', 'safe', 'same_kind', 'unsafe'}, optional
        Controls what kind of data casting may occur. Defaults to 'unsafe'
        for backwards compatibility.
    
          * 'no' means the data types should not be cast at all.
          * 'equiv' means only byte-order changes are al

> Like list, array also has many useful methods.

##### array.shape

In [44]:
pe_array

array([[ 10.09,  10.28,   2.21,   6.19,   8.24],
       [ 99.98,  87.68, 154.23, 162.12, 121.11]])

In [45]:
pe_array.shape # row, column # (2, 5)

(2, 5)

##### array.size

In [46]:
np.size(pe_array) # 2 x 5

10

##### array.transpose

In [47]:
pe_array

array([[ 10.09,  10.28,   2.21,   6.19,   8.24],
       [ 99.98,  87.68, 154.23, 162.12, 121.11]])

In [48]:
pe_array_TRANSPOSED =\
    np \
    .transpose(pe_array)

In [49]:
np.shape(pe_array_TRANSPOSED) # (5, 2)

(5, 2)

In [51]:
pe_array_TRANSPOSED

array([[ 10.09,  99.98],
       [ 10.28,  87.68],
       [  2.21, 154.23],
       [  6.19, 162.12],
       [  8.24, 121.11]])

> Remember how to subset nested lists? `Subsetting` two-dimensional arrays is similar to subsetting nested lists. 

> In a 2D array, the indexing/slicing should be specific to the dimension of the array: **`array[row, column]`**

##### How would you subset `earnings` from the `transposed pe_array`? 

In [52]:
pe_array

array([[ 10.09,  10.28,   2.21,   6.19,   8.24],
       [ 99.98,  87.68, 154.23, 162.12, 121.11]])

In [53]:
np.array([earnings_list, prices_list]) == pe_array

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [61]:
type(pe_array)

numpy.ndarray

In [63]:
pe_array.shape

(2, 5)

In [54]:
earnings = pe_array[ 0 , : ] # row, column
print(earnings)

[10.09 10.28  2.21  6.19  8.24]


In [55]:
earnings == pe_array_TRANSPOSED[ : , 0]

array([ True,  True,  True,  True,  True])

##### How would you subset `prices` from the `transposed pe_array`? 

In [56]:
prices = pe_array_TRANSPOSED[ : , 1 ]
print(prices)

[ 99.98  87.68 154.23 162.12 121.11]


##### How would you subset the `earnings and prices for third and forth companies` from the `transposed pe_array`?

In [57]:
pe_array_TRANSPOSED

array([[ 10.09,  99.98],
       [ 10.28,  87.68],
       [  2.21, 154.23],
       [  6.19, 162.12],
       [  8.24, 121.11]])

In [58]:
pe_34 = pe_array_TRANSPOSED[2:-1, : ]
print(pe_34)

[[  2.21 154.23]
 [  6.19 162.12]]


In [59]:
pe_array

array([[ 10.09,  10.28,   2.21,   6.19,   8.24],
       [ 99.98,  87.68, 154.23, 162.12, 121.11]])

In [60]:
pe_34 == pe_array[ : , 2:-1]

array([[ True, False],
       [False,  True]])

> ***Review & Expansion of Your Vocabulary: Below are some useful basics for array.***

In [64]:
pe_array

array([[ 10.09,  10.28,   2.21,   6.19,   8.24],
       [ 99.98,  87.68, 154.23, 162.12, 121.11]])

In [65]:
# Get Dimension
pe_array.ndim

2

In [66]:
# Get Shape
pe_array.shape

(2, 5)

In [67]:
# Get Type
pe_array.dtype

dtype('float64')

In [68]:
# Get Size (itemsize)
pe_array.itemsize

8

In [69]:
# Get total size (nbytes)
pe_array.nbytes

80

In [70]:
# Get number of elements (size)
pe_array.size

10

In [71]:
# Get a specific element [row, column]
pe_array[ : , 0] == pe_array[ : , -1]

array([False, False])

In [72]:
# Get a specific row 
pe_array

array([[ 10.09,  10.28,   2.21,   6.19,   8.24],
       [ 99.98,  87.68, 154.23, 162.12, 121.11]])

In [73]:
pe_array[1, : ]

array([ 99.98,  87.68, 154.23, 162.12, 121.11])

In [74]:
# Get a specific column
pe_array[ : , 3]

array([  6.19, 162.12])

In [75]:
# Getting a little more fancy [startindex:endindex:stepsize]
# let's do this with transposed 2d-array

pe_array_TRANSPOSED

array([[ 10.09,  99.98],
       [ 10.28,  87.68],
       [  2.21, 154.23],
       [  6.19, 162.12],
       [  8.24, 121.11]])

In [76]:
pe_array_TRANSPOSED[0:4:2, 0]

array([10.09,  2.21])

#### `WARNING`: Please be careful when `copying arrays`!

In [77]:
m = np.array([1, 2, 3])
n = m

n[0] = 4
n

array([4, 2, 3])

In [78]:
m

array([4, 2, 3])

In [79]:
help(pe_array.copy)

Help on built-in function copy:

copy(...) method of numpy.ndarray instance
    a.copy(order='C')
    
    Return a copy of the array.
    
    Parameters
    ----------
    order : {'C', 'F', 'A', 'K'}, optional
        Controls the memory layout of the copy. 'C' means C-order,
        'F' means F-order, 'A' means 'F' if `a` is Fortran contiguous,
        'C' otherwise. 'K' means match the layout of `a` as closely
        as possible. (Note that this function and :func:`numpy.copy` are very
        similar but have different default values for their order=
        arguments, and this function always passes sub-classes through.)
    
    See also
    --------
    numpy.copy : Similar function with different default behavior
    numpy.copyto
    
    Notes
    -----
    This function is the preferred method for creating an array copy.  The
    function :func:`numpy.copy` is similar, but it defaults to using order 'K',
    and will not pass sub-classes through by default.
    
    Exampl

In [80]:
p = np.array([5, 6, 7])
q = p.copy() # use copy() method
q[0] = 8
print(p) # [5, 6, 7]

[5 6 7]


### Mathematics with NumPy

> **`We all love mathematics`. For a lot more**, [check this out](https://docs.scipy.org/doc/numpy/reference/routines.math.html).

- For example, `linear algebra`, look at [here](https://docs.scipy.org/doc/numpy/reference/routines.linalg.html).

#### Statistics

> Not only can you perform element-wise calculations on NumPy arrays, you can also calculate summary statistics such as range, mean, and standard deviation of arrays using functions from NumPy.

##### Calculating the range (minimum and maximum values)

In [6]:
print(pe_array)

[[ 10.09  10.28   2.21   6.19   8.24]
 [ 99.98  87.68 154.23 162.12 121.11]]


In [7]:
pe_array.ndim

2

In [8]:
np \
    .max(pe_array)

162.12

In [9]:
np.min(pe_array)

2.21

In [10]:
np \
    .max(pe_array,
         axis = 1)

array([ 10.28, 162.12])

In [11]:
np.min(pe_array, 
       axis = 0)

array([10.09, 10.28,  2.21,  6.19,  8.24])

##### Calculating the mean (`mean`) and standard deviation (`std`)

In [12]:
%whos

Variable   Type       Data/Info
-------------------------------
np         module     <module 'numpy' from '/Us<...>kages/numpy/__init__.py'>
pe_array   ndarray    2x5: 10 elems, type `float64`, 80 bytes


In [13]:
pe_array

array([[ 10.09,  10.28,   2.21,   6.19,   8.24],
       [ 99.98,  87.68, 154.23, 162.12, 121.11]])

In [14]:
earnings_mean =\
    np \
    .mean(pe_array[0, : ]
         )

print(earnings_mean)

7.401999999999999


In [15]:
pe_array_TRANSPOSED =\
    np \
    .transpose(pe_array)

In [16]:
pe_array.shape

(2, 5)

In [17]:
pe_array_TRANSPOSED.shape

(5, 2)

In [18]:
np \
    .mean(pe_array_TRANSPOSED,
          axis = 0)

array([  7.402, 125.024])

In [19]:
pe_array

array([[ 10.09,  10.28,   2.21,   6.19,   8.24],
       [ 99.98,  87.68, 154.23, 162.12, 121.11]])

In [20]:
prices_std =\
    np \
    .std(pe_array[1, : ]
        )
print(prices_std)

29.210269837849836


In [21]:
np.std(pe_array,
       axis = 0)

array([44.945, 38.7  , 76.01 , 77.965, 56.435])

##### Generating a sequence of numbers

> Often you may want to create an array of a range of numbers (e.g., 1 to 500) without having to type in every single number. 

> The NumPy function `arange()` is an efficient way to create numeric arrays of a range of numbers--using arange() can be much faster than typing each individual element.

> The arguments for `arange()` include the `start`, `stop`, and `step interval` as follows: `np.arange(start, stop, step)`


In [22]:
help(np.arange)

Help on built-in function arange in module numpy:

arange(...)
    arange([start,] stop[, step,], dtype=None, *, like=None)
    
    Return evenly spaced values within a given interval.
    
    Values are generated within the half-open interval ``[start, stop)``
    (in other words, the interval including `start` but excluding `stop`).
    For integer arguments the function is equivalent to the Python built-in
    `range` function, but returns an ndarray rather than a list.
    
    When using a non-integer step, such as 0.1, the results will often not
    be consistent.  It is better to use `numpy.linspace` for these cases.
    
    Parameters
    ----------
    start : integer or real, optional
        Start of interval.  The interval includes this value.  The default
        start value is 0.
    stop : integer or real
        End of interval.  The interval does not include this value, except
        in some cases where `step` is not an integer and floating point
        round-off 

In [23]:
ticker_ids =\
    np \
    .arange(1, 1001, 1)

print(ticker_ids)

[   1    2    3    4    5    6    7    8    9   10   11   12   13   14
   15   16   17   18   19   20   21   22   23   24   25   26   27   28
   29   30   31   32   33   34   35   36   37   38   39   40   41   42
   43   44   45   46   47   48   49   50   51   52   53   54   55   56
   57   58   59   60   61   62   63   64   65   66   67   68   69   70
   71   72   73   74   75   76   77   78   79   80   81   82   83   84
   85   86   87   88   89   90   91   92   93   94   95   96   97   98
   99  100  101  102  103  104  105  106  107  108  109  110  111  112
  113  114  115  116  117  118  119  120  121  122  123  124  125  126
  127  128  129  130  131  132  133  134  135  136  137  138  139  140
  141  142  143  144  145  146  147  148  149  150  151  152  153  154
  155  156  157  158  159  160  161  162  163  164  165  166  167  168
  169  170  171  172  173  174  175  176  177  178  179  180  181  182
  183  184  185  186  187  188  189  190  191  192  193  194  195  196
  197 

> How would you create `odd numbers only`?

In [24]:
ticker_ids_odd =\
    np \
    .arange(1, 1001, 2)

print(ticker_ids_odd)

[  1   3   5   7   9  11  13  15  17  19  21  23  25  27  29  31  33  35
  37  39  41  43  45  47  49  51  53  55  57  59  61  63  65  67  69  71
  73  75  77  79  81  83  85  87  89  91  93  95  97  99 101 103 105 107
 109 111 113 115 117 119 121 123 125 127 129 131 133 135 137 139 141 143
 145 147 149 151 153 155 157 159 161 163 165 167 169 171 173 175 177 179
 181 183 185 187 189 191 193 195 197 199 201 203 205 207 209 211 213 215
 217 219 221 223 225 227 229 231 233 235 237 239 241 243 245 247 249 251
 253 255 257 259 261 263 265 267 269 271 273 275 277 279 281 283 285 287
 289 291 293 295 297 299 301 303 305 307 309 311 313 315 317 319 321 323
 325 327 329 331 333 335 337 339 341 343 345 347 349 351 353 355 357 359
 361 363 365 367 369 371 373 375 377 379 381 383 385 387 389 391 393 395
 397 399 401 403 405 407 409 411 413 415 417 419 421 423 425 427 429 431
 433 435 437 439 441 443 445 447 449 451 453 455 457 459 461 463 465 467
 469 471 473 475 477 479 481 483 485 487 489 491 49

> How would you create **`even`** numbers only then? 

In [25]:
ticker_ids_even = ticker_ids_odd + 1
print(ticker_ids_even)

[   2    4    6    8   10   12   14   16   18   20   22   24   26   28
   30   32   34   36   38   40   42   44   46   48   50   52   54   56
   58   60   62   64   66   68   70   72   74   76   78   80   82   84
   86   88   90   92   94   96   98  100  102  104  106  108  110  112
  114  116  118  120  122  124  126  128  130  132  134  136  138  140
  142  144  146  148  150  152  154  156  158  160  162  164  166  168
  170  172  174  176  178  180  182  184  186  188  190  192  194  196
  198  200  202  204  206  208  210  212  214  216  218  220  222  224
  226  228  230  232  234  236  238  240  242  244  246  248  250  252
  254  256  258  260  262  264  266  268  270  272  274  276  278  280
  282  284  286  288  290  292  294  296  298  300  302  304  306  308
  310  312  314  316  318  320  322  324  326  328  330  332  334  336
  338  340  342  344  346  348  350  352  354  356  358  360  362  364
  366  368  370  372  374  376  378  380  382  384  386  388  390  392
  394 

#### Boolean arrays can be a very powerful way to subset arrays. 

> As a case in point, let's try to identify the earnings that are greater than average from a list of earnings.

> To do so, let's find the mean value of earnings first.

In [26]:
pe_array

array([[ 10.09,  10.28,   2.21,   6.19,   8.24],
       [ 99.98,  87.68, 154.23, 162.12, 121.11]])

In [27]:
earnings_array =\
    pe_array[0, : ]

earnings_array

array([10.09, 10.28,  2.21,  6.19,  8.24])

In [28]:
mean_earnings =\
    np \
    .mean(earnings_array)

mean_earnings

7.401999999999999

In [29]:
bools_array = (mean_earnings > earnings_array)
bools_array

array([False, False,  True,  True, False])

##### How would you index earnings that are lesser than average

> Hint: You might want to create a boolean array first.

In [30]:
earnings_below_average =\
    earnings_array[mean_earnings > earnings_array]

In [31]:
earnings_below_average

array([2.21, 6.19])

In [32]:
earnings_below_average == earnings_array[bools_array]

array([ True,  True])

> Boolean array can be used for strings as well. 

> Let's create the names of companies with their associated industry first. 

> Here, your want to find all companies that are categorized as `Investment Services` industry.

##### How would you subset Investment Services industry and print companies in Investment Servecies?

In [81]:
!pip install numpy-financial


[notice] A new release of pip is available: 23.1.2 -> 23.2.1
[notice] To update, run: pip install --upgrade pip


In [82]:
import numpy_financial as npf

> For your information, there is numpy_financial package that contains a collection of elementary financial functions. 

> It will make your life easier when working with financial values.

> For example, the function .pv(rate, nper, pmt, fv) allows you to calculate the present value of an investment with some parameters:

- `rate` The rate of return of the investment
- `nper` The lifespan of the investment
- `pmt` The (fixed) payment at the beginning or end of each period
- `fv` The future value of the investment

> You can use this formula in many ways (e.g., you can calculate the present value of future investments in today's dollars).

> Before you run the code above, you should have installed the package `numpy-financial`.

In [83]:
investment_case =\
    npf \
    .pv(rate = 0.06,
        nper = 12,
        pmt = 0,
        fv = 50e3)

> Here, the present value returned is negative, so we multiply the result by -1

In [85]:
print("Your investment is worth " + str(round(-investment_case, 1)) + " in today's dollars.")

Your investment is worth 24848.5 in today's dollars.


In [86]:
dir(npf)

['__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_financial',
 'fv',
 'ipmt',
 'irr',
 'mirr',
 'nper',
 'npv',
 'pmt',
 'ppmt',
 'pv',
 'rate']

In [87]:
help(npf.fv)

Help on function fv in module numpy_financial._financial:

fv(rate, nper, pmt, pv, when='end')
    Compute the future value.
    
    Given:
     * a present value, `pv`
     * an interest `rate` compounded once per period, of which
       there are
     * `nper` total
     * a (fixed) payment, `pmt`, paid either
     * at the beginning (`when` = {'begin', 1}) or the end
       (`when` = {'end', 0}) of each period
    
    Return:
       the value at the end of the `nper` periods
    
    Parameters
    ----------
    rate : scalar or array_like of shape(M, )
        Rate of interest as decimal (not per cent) per period
    nper : scalar or array_like of shape(M, )
        Number of compounding periods
    pmt : scalar or array_like of shape(M, )
        Payment
    pv : scalar or array_like of shape(M, )
        Present value
    when : {{'begin', 1}, {'end', 0}}, {string, int}, optional
        When payments are due ('begin' (1) or 'end' (0)).
        Defaults to {'end', 0}.
    
   

> Similarly, you can also calculate the future value of an investment the following parameters:

- `rate` The rate of return of the investment
- `nper` The lifespan of the investment
- `pmt` The (fixed) payment at the beginning or end of each period (which is 0 in our example)
- `pv` The present value of the investment

> Here, you can use the function .fv(rate, nper, pmt, pv).

> Note that you should `input a negative value into the pv parameter` if it represents `a negative cash flow (cash going out)`. 

> That is, if you were to compute the future value of an investment, requiring an up-front cash payment, you would need to `input a negative value to the pv parameter` in the function .fv().

# Estimate Your Investment's Future Value

In [88]:
investment_fv =\
    npf \
    .fv(rate = 0.04,
        nper = 9,
        pmt = 0,
        pv = -60e3)

print("Your investment will return a total of $" + str(round(investment_fv, 1)) + " in 9 years!!!")

Your investment will return a total of $85398.7 in 9 years!!!


# Estimate the Future Value of Your Friend's Investment

##### Now let's adjust future values of your investment for inflation with the following steps:

**1. forecast the future value of an investment given a rate of return**

**2. discount the future value of the investment by a projected inflation rate**

> Here, we will `utilize both functions .fv() and .pv()` to estimate the projected value of a given investment in today's dollars, adjusted for inflation.

> ***Scenario***: `Investment returning 7% per year for 25 years`

In [89]:
your_friend_investment =\
    npf \
    .fv(rate = 0.07,
        nper = 25,
        pmt = 0,
        pv = -60e3)

print("Your friend's investment will return of a total of $" + str(round(your_friend_investment, 1)) + " in 25 years.")

Your friend's investment will return of a total of $325646.0 in 25 years.


> ***Scenario***: `Inflation rate of 2.5% per year for 25 years`

In [90]:
discount =\
    npf \
    .pv(rate = 0.025,
        nper = 25,
        pmt = 0,
        fv = your_friend_investment)

print("After adjusting for inflation, your friend's invesment is worth $" + str(round(-discount)) + " in today's dollars.")

After adjusting for inflation, your friend's invesment is worth $175650 in today's dollars.


> `Thank you for working with the script :)`